# fly.toml app configuration file generated for avatar-crew-backend on 2025-07-29T09:48:21+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avatar-crew-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
